services:
  user-service:
    build:
      context: ./user
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./user/.env

  hotel-service:
    build:
      context: ./hotel
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - ./hotel/.env

  booking-service:
    build:
      context: ./reservation
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    env_file:
      - ./reservation/.env

  payment-service:
    build:
      context: ./payment
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    env_file:
      - ./payment/.env